### ISSUE TITLE
Warning vanishes when on smaller screen

### ISSUE THREAD

**Issue by karmatosed** [WordPress/better-code-editing#11]
I was doing some testing on various screen sizes and discovered an oddity. This is what I see on desktop:

![1](https://user-images.githubusercontent.com/253067/28169753-372afbf8-67db-11e7-98fa-b3c14610fa10.png)

Yet, as soon as I reduce the screen size this happens:

![1nondesktop](https://user-images.githubusercontent.com/253067/28169768-41fa089e-67db-11e7-9a1d-6544b06ee59c.png)

The warnings aren't present at all.

**Comment by obenland** [comment]
I've spent a good amount of time today, trying to track that down. Currently it looks to me like this is a CodeMirror bug. Linen umbers are part of the core package and work differently than the rest of the information that is being displayed in the gutter. I'll try to dig deeper to find out
