### ISSUE TITLE
Is HTML meant to have no code coloring?

### ISSUE THREAD

**Issue by karmatosed** [WordPress/better-code-editing#12]
This may be the desired case but struck me as to why it has no coloring. Maybe I am trained by editor color schemes, but looking at this page compared to other ones made me think the plugin was broken.

![2017-07-13 at 15 08](https://user-images.githubusercontent.com/253067/28170404-3f052afe-67dd-11e7-8531-11a3107c1842.png)

**Comment by melchoyce** [comment]
Able to reproduce. Let's make sure the HTML styles are loaded, too.
