### ISSUE TITLE
Error message doesn't go away for a while despite empty content

### ISSUE THREAD

**Issue by karmatosed** [WordPress/better-code-editing#14]
This is almost the other side of the 'can it be slower on checking', but it's important as when there is no information to feedback on, the message shouldn't linger. It currently lurks around for a while.

![3](https://user-images.githubusercontent.com/253067/28172363-412bdcaa-67e3-11e7-89a6-1a552592163a.png)

**Comment by westonruter** [comment]
Yes. This server-sent message should be replaced with the client-side live messages. Basically the server-side syntax checking would be eliminated entirely in favor of client side checks. This would be done as part of the core merge, however.
