### ISSUE TITLE
Access to all files unlimited folder depth within the selected theme or plugin

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/better-code-editing#16]
At present going to the edit screen to edit for instance style.css or the functions.php works fine as these are usually in the root folder. Files one level deep will likely show up. 

Having stylesheets within assets/css/something.css  I assume because it is deeper then one level that it does not show up in the edit screen. This means I am not able to edit the something.css because of the lack of access to it in the WP backend. Which means I have to go through ftp.

**Comment by westonruter** [comment]
This would be out of scope for this ticket. I believe you may be looking for: https://core.trac.wordpress.org/ticket/6531

**Comment by paaljoachim** [comment]
Thanks! Hopefully the trac issue can be dealt with and fixed.
