### ISSUE TITLE
Decide on which modes and themes should be bundled with core

### ISSUE THREAD

**Issue by westonruter** [WordPress/better-code-editing#24]
There are about 120 modes that CodeMirror ships with: https://github.com/codemirror/CodeMirror/blob/5.28.0/mode/meta.js#L15-L168

The vast majority of these modes are not relevant to the kinds of types that will be modified in WordPress. Which ones should be included? At least there should be:

* `css`
* `htmlembedded`
* `htmlmixed`
* `javascript`
* `php`
* `sql`
* `xml`

But then what about:

* `diff`
* `http`
* `jsx`
* `shell`
* `sql`
* `yaml`

And then are there any others shat should be included? What about `twig`?

There is also then the question of `themes`. There are 48 different themes. Should we only include one? See https://github.com/codemirror/CodeMirror/tree/5.28.0/theme

**Comment by melchoyce** [comment]
Let's only include one theme in core by default, but consider making (or encourage someone else to make) a plugin that lets you swap them. I'll take a look at them this week and propose a default 👍

**Comment by kenashworth** [comment]
Ambiance is my personal fav.

**Comment by kenashworth** [comment]
Markdown (and maybe github flavored markdown) might be good to include too

**Comment by melchoyce** [comment]
Color schemes all demo'd here: http://codemirror.net/demo/theme.html

**Comment by melchoyce** [comment]
These are the color schemes I think are the most legible and attractive:
- http://codemirror.net/demo/theme.html#default
- http://codemirror.net/demo/theme.html#base16-dark
- http://codemirror.net/demo/theme.html#bespin
- http://codemirror.net/demo/theme.html#elegant
- http://codemirror.net/demo/theme.html#material
- http://codemirror.net/demo/theme.html#xq-light

I'm thinking we should either go with default, or roll our own, like: https://gist.github.com/melchoyce/1f1dcf2307e8f699a6122c8399db54f1

**Comment by westonruter** [comment]
I've removed all the themes from being bundled, leaving only the default. A plugin can bundle those themes to enqueue as desired. I've also added the modes I think make sense. See #66.
