### ISSUE TITLE
Scroll jank in the Customizer

### ISSUE THREAD

**Issue by melchoyce** [WordPress/better-code-editing#32]
![css](https://user-images.githubusercontent.com/2846578/29381943-fc3cab94-8298-11e7-9d15-8a18b6ad5ea6.gif)

**Comment by westonruter** [comment]
I can reproduce this in Firefox only. It does not occur in Chrome or Safari.

**Comment by westonruter** [comment]
This is reported upstream: https://github.com/codemirror/CodeMirror/issues/3705

**Comment by melchoyce** [comment]
Weird, I was testing in Chrome /shrug
