### ISSUE TITLE
Editor width doesn't account for extra space

### ISSUE THREAD

**Issue by melchoyce** [WordPress/better-code-editing#5]
The inclusion of the line numbers increases the overall width of the editor, so it cuts into the list of files on the side:

**With:**

![image](https://user-images.githubusercontent.com/2846578/27749137-4325efde-5da0-11e7-85cf-cc322655c01e.png)

**Without:**

![image](https://user-images.githubusercontent.com/2846578/27749188-87ac65e8-5da0-11e7-8635-d7f0424aed9d.png)

The editor should remain the same width, with the line numbers taking up room inside, rather than outside.

**Comment by melchoyce** [comment]
Related: https://core.trac.wordpress.org/ticket/41309 cc @karmatosed

**Comment by westonruter** [comment]
@melchoyce I don't think this is a problem. The main difference between the two editors, actually, is that CodeMirror does not wrap lines whereas a `textarea` does. We could enable `lineWrapping` option and that results in:

![image](https://user-images.githubusercontent.com/134745/29383274-b0772522-8284-11e7-9a7c-3f83b02c836a.png)

I'll also note that adding line-wrapping is a workaround fix for #32 as well.

**Comment by melchoyce** [comment]
Line-wrapping is good 👍 But the extra width is still a problem — notice in my before/after how the editor starts to run very close to the file list.

**Comment by melchoyce** [comment]
![image](https://user-images.githubusercontent.com/2846578/29463242-0a431a1c-8400-11e7-8d7d-8f635c8223ab.png)

**Comment by westonruter** [comment]
> But the extra width is still a problem — notice in my before/after how the editor starts to run very close to the file list.

Oh I see now. Fixed in https://github.com/WordPress/codemirror-wp/pull/33/commits/74859d1f4e8b8474e792475b86ba54527393241d via #33.
