### ISSUE TITLE
Use npm to import CodeMirror instead of submodule

### ISSUE THREAD

**Issue by WraithKenny** [WordPress/better-code-editing#7]
Since you require npm building CodeMirror anyway, maybe it'd make sense to use npm to install it instead? Or even a nice Gulp script to concatenate, minify, and move into a non-modules location?

**Comment by WraithKenny** [comment]
Or is this because you need to bundle the source code for GPL reasons?

**Comment by westonruter** [comment]
@WraithKenny how's #23 look?

**Comment by WraithKenny** [comment]
I can test it out tomorrow, but sounds good to me :-)
