### ISSUE TITLE
Fatal error upon activation

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/better-code-editing#73]
I cloned this into wp-content/plugins.  When I activated the plugin, my site stopped working. 
`Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/srv/www/wordpress-develop/public_html/src/wp-content/plugins/better-code-editing/wp-includes/js/codemirror): failed to open dir: No such file or directory in /srv/www/wordpress-develop/public_html/src/wp-content/plugins/better-code-editing/wp-includes/script-loader-addendum.php:197 Stack trace: #0 /srv/www/wordpress-develop/public_html/src/wp-content/plugins/better-code-editing/wp-includes/script-loader-addendum.php(197): RecursiveDirectoryIterator->__construct('/srv/www/wordpr...') #1 /srv/www/wordpress-develop/public_html/src/wp-content/plugins/better-code-editing/wp-includes/script-loader-addendum.php(127): _better_code_editing_report_asset_errors(Object(WP_Scripts)) #2 /srv/www/wordpress-develop/public_html/src/wp-includes/class-wp-hook.php(286): _better_code_editing_default_scripts(Object(WP_Scripts)) #3 /srv/www/wordpress-develop/public_html/src/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #4 /srv/www/ in /srv/www/wordpress-develop/public_html/src/wp-content/plugins/better-code-editing/wp-includes/script-loader-addendum.php on line 197`

**Comment by westonruter** [comment]
@aaronjorbin please use a release build either on WordPress.org or among releases on GitHub: https://github.com/WordPress/better-code-editing/releases

To install the plugin from source, follow the instructions here: https://github.com/WordPress/better-code-editing/blob/master/contributing.md#getting-started

**Comment by westonruter** [comment]
That being said, the plugin could check if `wp-includes/js/codemirror` exists and if not, prompt the user to run `npm install`.
