### ISSUE TITLE
In Chrome, browser based search doesn't search file contents

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/better-code-editing#75]

**Comment by aaronjorbin** [comment]
Not all of the file is actually searched when using the browser based search. 

![code-editing-search mov](https://user-images.githubusercontent.com/622599/29932025-11b009b8-8e41-11e7-9426-c5236d32d568.gif)

**Comment by westonruter** [comment]
@aaronjorbin CodeMirror has a search addon: https://codemirror.net/demo/search.html

Including that should solve this problem, yes?
