### ISSUE TITLE
Auto-expand Additional CSS section description when CSS is empty

### ISSUE THREAD

**Issue by westonruter** [WordPress/better-code-editing#79]
To help orient users to what Additional CSS is, the section description could be auto-expanded when first opening the panel, when the CSS is empty or at its placeholder value. The help text was improved in #36 via #65.

![image](https://user-images.githubusercontent.com/134745/30035260-08b0c0ae-915d-11e7-97d0-fa1df4873cde.png)

A close button could be added for a user to dismiss the description, so the user doesn't have to click the Help icon again.

See conversation at https://wordpress.slack.com/archives/C02RP4X03/p1504546313000167

**Comment by melchoyce** [comment]
I'm game. Let's try a right-aligned "Close" link on the bottom right of the description.
