### ISSUE TITLE
Keyboard focus when Help section is open

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/better-code-editing#90]
I notices this keyboard navigation in Additional CSS.

1. Help section is open.
1. I'm inside CSS fields (writing CSS).
1. I press Esc + Shift + Tab.
1. My focus moves to ?-help-button.

In my opinion it should move to last focusable item in the help section (Close button in this case).

If the help section is closed, then focus should move to ?-help-button.

**Comment by westonruter** [comment]
Good point. The close button was added after the tab-precious logic was implemented so it is not being taken into account. Also I assumed the user would close the help description first, but clearly that's not the case.
